# Generated by Django 4.2.30 on 2026-06-08 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_payment_options'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='payment_method',
        # ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 8, 10, 34, 20, 993869, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
    ]
