# Generated by Django 4.2.30 on 2026-06-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_payment_appointment_alter_payment_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='PAYMENT',
        ),
    ]
