# Generated by Django 4.2.30 on 2026-06-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_rename_payment_date_payment_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'managed': False},
        ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='payment_method',
        # ),
    ]
